server:
    contextPath: /kris-kringle
    port: 9821

management:
    security:
        enabled: false
    
spring:
    application:
        name: kris-kringle
    profiles:
        active: dev
    datasource:
            url: jdbc:mysql://localhost:3306/kriskringledb?useSSL=false
            databaseName: kriskringledb
            username: springuser
            password: password
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false               